### ISSUE TITLE
Error drawing barchart

### ISSUE THREAD

**Issue by robertovaldesperez** [ignoreintuition/v-chart-plugin#194]
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

import Chart from 'v-chart-plugin'
Vue.use(Chart)

`<v-chart v-if="listLoading" :chart-data="barChartData" />`

**Comment by ignoreintuition** [comment]
Duplicate of another issue

**Comment by robertovaldesperez** [comment]
I'm sorry
