### ISSUE TITLE
Add eslint configuration for project

### ISSUE THREAD

**Issue by ignoreintuition** [ignoreintuition/v-chart-plugin#66]
We don't currently have any ESLint configuration.  Would need someone to install / configure eslint using airbnb standards: https://www.npmjs.com/package/eslint-config-airbnb-standard

**Comment by romainwn** [comment]
Hey ! I'd like to take care of this issue :)

**Comment by ignoreintuition** [comment]
Please do. Checkout the development branch

**Comment by romainwn** [comment]
So, I just installed it, but got 12938 problemes lol
Should I fix them in the same PR ? or is this PR just about adding it to the project ?

**Comment by ignoreintuition** [comment]
I assume a lot of them are formatting issues. Feel free to make any changes you feel comfortable with. I appreciate all your help.

**Comment by ignoreintuition** [comment]
Come to think of it it might be better to treat that as a separate issue. I’ll add another issue to the repo so we can close this one out since the work is done. I won’t have a chance to take a look at it till this evening but if you want to work on the other issue I welcome the help

**Comment by romainwn** [comment]
I won't be able to work on this for now, but I can sure give it a try later !
