### ISSUE TITLE
Clean up jsdocs

### ISSUE THREAD

**Issue by ignoreintuition** [ignoreintuition/v-chart-plugin#74]
Need someone to go through and fix up the comments on all the functions so that the jsDocs are accurate.

**Comment by kndarp** [comment]
Hi! 
I'd like to contribute to this.

**Comment by ignoreintuition** [comment]
That would be fantastic. Very much appreciated. Please branch off of development and submit your PR back to development. If you have any questions reach out to me or check the contributor guidelines in the github wiki.

**Comment by ignoreintuition** [comment]
Thank you @kndarp.  I have checked these changes into development.
