### ISSUE TITLE
Unable to import v-chart-plugin

### ISSUE THREAD

**Issue by natemara** [ignoreintuition/v-chart-plugin#92]
I'm not able to import v-chart plugin from my node_modules. I created an empty runkit notebook that illustrates the problem: https://runkit.com/natemara/v-chart-plugin-test.

![2018-10-27 10_05_31-window](https://user-images.githubusercontent.com/6109875/47605083-f237c900-d9cf-11e8-8c55-7062ad3884b0.png)

You can see that it finds the version, so it does have the package installed, it's just some problem with the way that this library is exported. I think it may be because the package.json has no `main` field. Can this be added?

**Comment by ignoreintuition** [comment]
I just published a change so it should be pulling in the plugin from v 0.2.6.  It is giving an error with babel transpilation.  Looking into that now

**Comment by ignoreintuition** [comment]
v 0.2.8 pulls in the transpiled code.  I have tested end-to-end and everything appears to be working.  Closing this issue.  If the issue resurfaces please let me know @natemara .
